# full inventory message: use '&' symbol for color codes
full_inventory_message: "&cYour inventory is now &6full!"
# auto collecting experience true = enable, false = disable
auto_experience: true
# list the worlds you want to enable the plugin on.
enabled_worlds:
  - world
# list the worlds you want to disable the plugin on.
disabled_worlds:
  - world2
